# LIST individuals and their date of birth

PREFIX : <http://purl.org/ejp-rd/phenopackets-rdf-schema/v010/example-rdf/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?individual ?attribute ?attribute_value {
  
  # GET individual and their attributes	
  ?individual a sio:SIO_000498;
  		sio:SIO_000008 ?attribute.
  
  # GET attribute and its value
  ?attribute a sio:SIO_000614;
        sio:SIO_000332 obo:NCIT_C68615;       
  		sio:SIO_000300 ?attribute_value.
}
