# LIST individuals and its attributes  

PREFIX sio: <http://semanticscience.org/resource/>

SELECT DISTINCT ?individual ?attribute ?attribute_value {
  
  # GET individual and their attributes	
  ?individual a sio:SIO_000498;
  		sio:SIO_000008 ?attribute.
  
  # GET attribute and its value
  ?attribute a sio:SIO_000614;               
  		sio:SIO_000300 ?attribute_value
}
